config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :products
  resources :destinations do
    collection do
      post :assign_route
      get :routed_products
    end
  end

  root 'destinations#routed_products'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/destination.rb
class Destination < ApplicationRecord
  serialize :references
  serialize :categories

  has_many :products

  validates :name, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :destination, optional: true

  validates :name, :reference, :category, :price, presence: true

  scope :routed, -> { where.not(destination_id: nil) }
  scope :unrouted, -> { where(destination_id: nil) }

  def self.categories
    pluck(:category).uniq.sort
  end

  def self.references
    pluck(:reference).uniq.sort
  end

  def assign_route!
    ::RouteProduct.new(self).call
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :fetch_product_options_meta, only: [:new, :edit, :create, :update]
  before_action :find_destination, only: [:edit, :update, :show, :destroy]

  def index
    @destinations = Destination.page(params[:page])
  end

  def routed_products
    @routed_products = Product.routed.page(params[:page])
    @unrouted_products = Product.unrouted
    @hide_action = true
  end

  def new
    @destination = Destination.new
  end

  def create
    @destination = Destination.new
    @destination.assign_attributes(destination_params)

    if @destination.valid?
      @destination.save

      redirect_to destinations_path, notice: 'Created new destination.'
    else
      render action: :new, status: :unprocessable_entity
    end
  end

  def update
    @destination.assign_attributes(destination_params)

    if @destination.valid?
      @destination.save

      redirect_to destination_path(@destination), notice: 'Destination Updated'
    else
      render action: :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @destination.destroy

    redirect_to destinations_path, notice: 'Destination Deleted'
  end

  def assign_route
    Product.find(params[:product_id]).assign_route!

    redirect_to routed_products_destinations_path, notice: 'Products were routed.'
  end

  private

    def destination_params
      params.require(:destination).permit(:name, :maximum_price, references: [], categories: [])
    end

    def find_destination
      @destination = Destination.find(params[:id])
    end

    def fetch_product_options_meta
      @product_categories = Product.categories
      @product_references = Product.references
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:edit, :update, :show, :destroy]

  def index
    @products = Product.page(params[:page])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.valid?
      @product.save

      redirect_to products_path, notice: 'Product Created'
    else
      render action: :new, status: :unprocessable_entity
    end
  end

  def update
    @product.assign_attributes(product_params)

    if @product.valid?
      @product.save

      redirect_to product_path(@product), notice: 'Product Updated'
    else
      render action: :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy

    redirect_to products_path, notice: 'Product Deleted'
  end

  private

    def find_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :price, :reference, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/destinations/_assign_route_form.html.erb
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header d-flex justify-content-between">
        <span>Assign Route</span>
        <%= link_to 'New Destination', new_destination_path, class: 'btn btn-outline-info btn-sm' %>
      </div>
      <div class="card-body">
        <%= form_tag(assign_route_destinations_path, method: :post) do %>
          <div class="row">
            <div class="col">
              <%= select_tag 'product_id', options_from_collection_for_select(@unrouted_products, 'id', 'name'), prompt: 'Select product', class: 'form-control' %>
            </div>
            <div class="col">
              <%= submit_tag "Assign route", data: { disable_with: "Assigning..." }, class: 'btn btn-outline-info' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/destinations/_destination.html.erb
<tr>
  <td><%= destination.id %></td>
  <td><%= destination.name %></td>
  <td><%= destination.maximum_price %></td>
  <td><%= destination.categories.join(' ') %></td>
  <td><%= destination.references.join(' ') %></td>
  <td>
    <div class="btn-group" role="group" aria-label="Actions">
      <%= link_to 'View', destination_path(destination), class: 'btn btn-outline-info' %>
      <%= link_to 'Edit', edit_destination_path(destination), class: 'btn btn-outline-info' %>
      <%= link_to 'Delete', destination_path(destination), class: 'btn btn-outline-danger', data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    </div>
  </td>
</tr>

app/views/destinations/_form.html.erb
<%= simple_form_for @destination do |f| %>
    <%= f.input :name %>
    <%= f.input :maximum_price %>
    <%= f.input :references, collection: @product_references, input_html: { multiple: true }, include_blank: true  %>
    <%= f.input :categories, collection: @product_categories, input_html: { multiple: true }, include_blank: true  %>
  <%= f.submit 'Save', class: 'btn btn-outline-success btn-block' %>
<% end %>

app/views/destinations/edit.html.erb
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header d-flex justify-content-between">
        <span>Edit Destination</span>
        <%= link_to 'Back', destinations_path, class: 'btn btn-outline-info btn-sm' %>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/destinations/index.html.erb
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header d-flex justify-content-between">
        <span>Destinations</span>
        <%= link_to 'New Destination', new_destination_path, class: 'btn btn-outline-info btn-sm' %>
      </div>
      <div class="card-body">
        <table class="table table-striped table-hover">
          <thead>
            <th>ID</th>
            <th>Name</th>
            <th>Maximum Price</th>
            <th>Categories</th>
            <th>References</th>
            <th>Actions</th>
          </thead>
          <tbody>
            <%= render @destinations %>
          </tbody>
        </table>
      </div>
      <div class="card-footer d-flex justify-content-center pt-3">
        <%= paginate @destinations %>
      </div>
    </div>
  </div>
</div>

app/views/destinations/new.html.erb
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header d-flex justify-content-between">
        <span>Create Destination</span>
        <%= link_to 'Back', destinations_path, class: 'btn btn-outline-info btn-sm' %>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/destinations/routed_products.html.erb
<%= render 'assign_route_form' %>

<div class="row mt-5">
  <div class="col">
    <div class="card">
      <div class="card-header d-flex justify-content-between">
        <span>Routed Products</span>
      </div>
      <div class="card-body">
        <table class="table table-striped table-hover">
          <thead>
            <th>ID</th>
            <th>Name</th>
            <th>Price</th>
            <th>Category</th>
            <th>Reference</th>
            <th>Destination</th>
          </thead>
          <tbody>
            <%= render @routed_products %>
          </tbody>
        </table>
      </div>
      <div class="card-footer d-flex justify-content-center pt-3">
        <%= paginate @routed_products %>
      </div>
    </div>
  </div>
</div>

app/views/destinations/show.html.erb
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header d-flex justify-content-between">
        <span>Destination Details</span>
        <div class="btn-group" role="group" aria-label="Actions">
          <%= link_to 'Destinations List', destinations_path, class: 'btn btn-outline-info' %>
          <%= link_to 'Edit', edit_destination_path(@destination), class: 'btn btn-outline-info' %>
          <%= link_to 'Delete', destination_path(@destination), class: 'btn btn-outline-danger', data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        </div>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col col-md-1">ID:</div>
          <div class="col"><%= @destination.id %></div>
        </div>

        <div class="row">
          <div class="col col-md-1">Name:</div>
          <div class="col"><%= @destination.name %></div>
        </div>

        <div class="row">
          <div class="col col-md-1">Maximum Price:</div>
          <div class="col"><%= @destination.maximum_price %></div>
        </div>

        <div class="row">
          <div class="col col-md-1">Reference:</div>
          <div class="col"><%= @destination.references.join(' ') %></div>
        </div>

        <div class="row">
          <div class="col col-md-1">Category:</div>
          <div class="col"><%= @destination.categories.join(' ') %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuybayExam</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true, type: "module" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="header">
      <%= render 'shared/header' %>
    </div>
    <div class="body-content pt-3">
      <div class="container-fluid">
        <%= render 'shared/flash' %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
  <%= f.input :name %>
  <%= f.input :price %>
  <%= f.input :reference %>
  <%= f.input :category %>
  <div class="row">
    <div class="col d-grid">
      <%= link_to 'Cancel', products_path, class: 'btn btn-outline-info btn-block' %>
    </div>
    <div class="col d-grid">
      <%= f.submit 'Save', class: 'btn btn-outline-success btn-block' %>
    </div>
  </div>
<% end %>

app/views/products/_product.html.erb
<tr>
  <td><%= product.id %></td>
  <td><%= product.name %></td>
  <td><%= product.price %></td>
  <td><%= product.category %></td>
  <td><%= product.reference %></td>
  <td><%= product.destination&.name %></td>
  <% unless @hide_action %>
  <td>
    <div class="btn-group" role="group" aria-label="Actions">
      <%= link_to 'View', product_path(product), class: 'btn btn-outline-info' %>
      <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-outline-info' %>
      <%= link_to 'Delete', product_path(product), class: 'btn btn-outline-danger', data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    </div>
  </td>
  <% end %>
</tr>

app/views/products/edit.html.erb
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header d-flex justify-content-between">
        <span>Edit Product</span>
        <%= link_to 'Back', products_path, class: 'btn btn-outline-info btn-sm' %>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header d-flex justify-content-between">
        <span>Products</span>
        <%= link_to 'New Product', new_product_path, class: 'btn btn-outline-info btn-sm' %>
      </div>
      <div class="card-body">
        <table class="table table-striped table-hover">
          <thead>
            <th>ID</th>
            <th>Name</th>
            <th>Price</th>
            <th>Category</th>
            <th>Reference</th>
            <th>Destination</th>
            <th>Actions</th>
          </thead>
          <tbody>
            <%= render @products %>
          </tbody>
        </table>
      </div>
      <div class="card-footer d-flex justify-content-center pt-3">
        <%= paginate @products %>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header d-flex justify-content-between">
        <span>New Product</span>
        <%= link_to 'Back', products_path, class: 'btn btn-outline-info btn-sm' %>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header d-flex justify-content-between">
        <span>Product Details</span>
        <div class="btn-group" role="group" aria-label="Actions">
          <%= link_to 'Product List', products_path, class: 'btn btn-outline-info' %>
          <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-outline-info' %>
          <%= link_to 'Delete', product_path(@product), class: 'btn btn-outline-danger', data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        </div>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col col-md-1">ID:</div>
          <div class="col"><%= @product.id %></div>
        </div>

        <div class="row">
          <div class="col col-md-1">Name:</div>
          <div class="col"><%= @product.name %></div>
        </div>

        <div class="row">
          <div class="col col-md-1">Price:</div>
          <div class="col"><%= @product.price %></div>
        </div>

        <div class="row">
          <div class="col col-md-1">Reference:</div>
          <div class="col"><%= @product.reference %></div>
        </div>

        <div class="row">
          <div class="col col-md-1">Category:</div>
          <div class="col"><%= @product.category %></div>
        </div>

        <div class="row">
          <div class="col col-md-1">Destination:</div>
          <div class="col"><%= @product.destination&.name %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show mt-3 mb-3" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show mt-3 mb-3" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">BuyBay Exam</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', routed_products_destinations_path, class: 'nav-link', aria: { current: 'page' } %>
        </li>
        <li class="nav-item">
          <%= link_to 'Products', products_path, class: 'nav-link', aria: { current: 'page' } %>
        </li>
        <li class="nav-item">
          <%= link_to 'Destinations', destinations_path, class: 'nav-link', aria: { current: 'page' } %>
        </li>
      </ul>
    </div>
  </div>
</nav>